# Generated by Django 4.2.16 on 2024-10-21 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('state', models.IntegerField()),
                ('coordinates', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddressO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('state', models.IntegerField()),
                ('coordinates', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('corporation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addresso')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_destiny', to='myapp.addressd')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_origin', to='myapp.addresso')),
            ],
        ),
    ]
