# Generated by Django 3.2.10 on 2024-12-12 21:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrier_type', models.CharField(choices=[('us', 'United States-based Carrier'), ('international', 'International Carrier')], default='us', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('DOT_number', models.CharField(blank=True, max_length=20, null=True)),
                ('license_guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='carrieruser_groups', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='carrieruser_permissions', to='auth.Permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AddressD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zip_code', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddressO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zip_code', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('corporation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('dotnumber', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('idmmequipment', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('idmmjob', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('idmmload', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(max_length=100)),
                ('loaded_miles', models.IntegerField()),
                ('total_weight', models.IntegerField()),
                ('commodity', models.CharField(max_length=100)),
                ('classifications_and_certifications', models.CharField(max_length=255)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_offerted', models.BooleanField(default=False)),
                ('number_of_offers', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_reserved', models.BooleanField(default=False)),
                ('tracking_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='not_started', help_text="Status of the load's transportation", max_length=20)),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Date and time when the load offer expires', null=True)),
                ('current_location', models.CharField(blank=True, help_text="Current location of the load in 'latitude,longitude' format", max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_destiny', to='myapp.addressd')),
                ('equipment', models.ForeignKey(blank=True, help_text='Required equipment for this load', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='myapp.equipmenttype')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_origin', to='myapp.addresso')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarningList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción del tipo de advertencia', max_length=255, unique=True)),
                ('issue_level', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, help_text='Nivel del problema')),
                ('is_active', models.BooleanField(default=False, help_text='Indica si el tipo de advertencia está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del tipo de advertencia')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del tipo de advertencia')),
            ],
            options={
                'verbose_name': 'Warning Type',
                'verbose_name_plural': 'Warning Types',
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('load', models.ForeignKey(blank=True, help_text='Carga asociada a esta advertencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_warnings', to='myapp.load')),
                ('reported_by', models.ForeignKey(blank=True, help_text='Usuario que reportó la advertencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_warnings', to=settings.AUTH_USER_MODEL)),
                ('warning_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='myapp.warninglist')),
            ],
            options={
                'verbose_name': 'Warning',
                'verbose_name_plural': 'Warnings',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('action_type', models.CharField(choices=[('live_load', 'Live Load'), ('dropped_trailer', 'Dropped Trailer'), ('other', 'Other'), ('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=50)),
                ('estimated_weight', models.IntegerField(validators=[myapp.models.validate_positive_weight])),
                ('quantity', models.IntegerField(validators=[myapp.models.validate_positive_quantity])),
                ('coordinates', models.CharField(max_length=100)),
                ('loaded_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='myapp.load')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='OfferHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[myapp.models.validate_positive_amount])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('terms_change', models.BooleanField(default=False)),
                ('proposed_pickup_date', models.DateField(blank=True, null=True)),
                ('proposed_pickup_time', models.TimeField(blank=True, null=True)),
                ('proposed_delivery_date', models.DateField(blank=True, null=True)),
                ('proposed_delivery_time', models.TimeField(blank=True, null=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_history', to='myapp.load')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer History',
                'verbose_name_plural': 'Offer Histories',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='load',
            name='warnings',
            field=models.ManyToManyField(blank=True, help_text='Advertencias asociadas a esta carga', related_name='loads', to='myapp.Warning'),
        ),
        migrations.AddField(
            model_name='addresso',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_addresses', to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='addressd',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_addresses', to='myapp.customer'),
        ),
        migrations.AddIndex(
            model_name='offerhistory',
            index=models.Index(fields=['date'], name='myapp_offer_date_f640b5_idx'),
        ),
        migrations.AddIndex(
            model_name='offerhistory',
            index=models.Index(fields=['status'], name='myapp_offer_status_762d77_idx'),
        ),
    ]
