# Generated by Django 5.1.5 on 2025-04-24 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressd',
            name='arrival_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Estimated or actual arrival datetime at the destination'),
        ),
        migrations.AddField(
            model_name='addresso',
            name='arrival_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Estimated or actual arrival datetime at the origin'),
        ),
    ]
