# Generated by Django 5.1.2 on 2025-01-05 02:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=255)),
                ('step', models.CharField(max_length=255)),
                ('pending_for_approval', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(upload_to='progress_pictures/')),
                ('idmmload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='myapp.load')),
            ],
        ),
    ]
