# Generated by Django 5.1.2 on 2025-01-11 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_loadprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrieruser',
            name='number_of_trucks',
            field=models.PositiveIntegerField(default=0, help_text='Number of trucks owned by the carrier'),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='Truck license plate', max_length=20, unique=True)),
                ('model', models.CharField(help_text='Truck model', max_length=50)),
                ('equipment_type', models.ForeignKey(blank=True, help_text='Type of equipment the truck is compatible with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.equipmenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
