# Generated by Django 5.1.2 on 2024-12-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_warninglist_issue_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warninglist',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
