# Generated by Django 4.2.16 on 2024-10-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_equipmenttype_remove_addressd_id_remove_addresso_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('idmmjob', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
