# Generated by Django 4.2.16 on 2024-10-25 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='classifications_and_certifications',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='commodity',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='loaded_miles',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='total_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('action_type', models.CharField(choices=[('live_load', 'Live Load'), ('dropped_trailer', 'Dropped Trailer')], max_length=50)),
                ('estimated_weight', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('loaded_on', models.CharField(blank=True, max_length=50, null=True)),
                ('coordinates', models.CharField(max_length=255)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='myapp.load')),
            ],
        ),
    ]
