# Generated by Django 5.1.2 on 2025-01-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_carrieruser_number_of_trucks_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Indicates if the load is closed.'),
        ),
    ]
