# Generated by Django 5.1.2 on 2024-12-10 03:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_warninglist_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warning',
            options={'verbose_name': 'Warning', 'verbose_name_plural': 'Warnings'},
        ),
        migrations.AlterModelOptions(
            name='warninglist',
            options={'verbose_name': 'Warning Type', 'verbose_name_plural': 'Warning Types'},
        ),
        migrations.AddField(
            model_name='warninglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 10, 3, 44, 36, 519618, tzinfo=datetime.timezone.utc), help_text='Fecha de creación del tipo de advertencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warninglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del tipo de advertencia'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='load',
            field=models.ForeignKey(blank=True, help_text='Carga asociada a esta advertencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_warnings', to='myapp.load'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que reportó la advertencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='warning_type',
            field=models.ForeignKey(help_text='Tipo de advertencia', on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='myapp.warninglist'),
        ),
        migrations.AlterField(
            model_name='warninglist',
            name='description',
            field=models.CharField(help_text='Descripción del tipo de advertencia', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='warninglist',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si el tipo de advertencia está activo'),
        ),
        migrations.AlterField(
            model_name='warninglist',
            name='issue_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, help_text='Nivel del problema'),
        ),
    ]
