# Generated by Django 3.2.10 on 2025-01-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_load_is_closed'),
        ('myapp', '0004_userpermission'),
    ]

    operations = [
    ]
