# Generated by Django 5.1.2 on 2024-12-10 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_warning_options_alter_warninglist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='warning_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='myapp.warninglist'),
        ),
    ]
