# Generated by Django 4.2.16 on 2024-10-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_load_classifications_and_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressd',
            name='idmmdestiny',
        ),
        migrations.RemoveField(
            model_name='addresso',
            name='idmmorigin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='idmmcustomer',
        ),
        migrations.RemoveField(
            model_name='load',
            name='idmmload',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='stop_number',
        ),
        migrations.AddField(
            model_name='addressd',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresso',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load',
            name='commodity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='load',
            name='loaded_miles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='load',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load',
            name='total_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='action_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stop',
            name='coordinates',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stop',
            name='estimated_weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='loaded_on',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
