# Generated by Django 5.1.5 on 2025-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_0004_load_is_closed_0004_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='honest_id',
            field=models.CharField(blank=True, help_text='ID proveniente de un correo de truck availability u otra fuente', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='load',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Indica si la carga está en revisión y no se muestra hasta que sea aprobada.'),
        ),
        migrations.AlterField(
            model_name='load',
            name='loaded_miles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='total_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
