# Generated by Django 4.2.16 on 2024-11-02 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_load_user'),
        ('myapp', '0006_remove_customer_address_remove_load_id_and_more'),
    ]

    operations = [
    ]
