# Generated by Django 4.2.16 on 2024-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_customer_address_remove_load_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dotnumber',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressd',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='addresso',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
