# Generated by Django 5.1.5 on 2025-02-10 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_load_honest_id_load_under_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_status', models.CharField(choices=[('on_time', 'On Time'), ('delayed', 'Delayed'), ('issue', 'Issue at Stop')], default='on_time', max_length=20)),
                ('delay_reason', models.CharField(blank=True, choices=[('traffic', 'Traffic'), ('weather', 'Weather Conditions'), ('mechanical', 'Mechanical Failure'), ('loading', 'Loading Issues'), ('unloading', 'Unloading Issues'), ('route_change', 'Route Change'), ('inspection', 'Inspection Delay'), ('other', 'Other')], max_length=50, null=True)),
                ('estimated_delay_time', models.PositiveIntegerField(blank=True, help_text='Estimated delay time in minutes', null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, help_text='Estimated arrival date and time', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='myapp.stop')),
            ],
            options={
                'verbose_name': 'Delay',
                'verbose_name_plural': 'Delays',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stop_status'], name='myapp_delay_stop_st_94950c_idx'), models.Index(fields=['delay_reason'], name='myapp_delay_delay_r_350436_idx')],
            },
        ),
    ]
