# Generated by Django 4.2.16 on 2024-11-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customer_dotnumber_alter_addressd_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dotnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
