# Generated by Django 4.2.16 on 2024-11-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_merge_20241102_0201'),
        ('myapp', '0008_alter_customer_dotnumber'),
    ]

    operations = [
    ]
