# Generated by Django 4.2.16 on 2024-11-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_merge_20241105_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
