# Generated by Django 4.2.16 on 2024-11-13 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_load_user_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='is_offerted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='load',
            name='number_of_offers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OfferHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_history', to='myapp.load')),
            ],
        ),
    ]
