# Generated by Django 3.2.10 on 2024-11-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_processedemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='customer',
        ),
        migrations.AddField(
            model_name='offerhistory',
            name='proposed_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerhistory',
            name='proposed_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerhistory',
            name='proposed_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerhistory',
            name='proposed_pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerhistory',
            name='terms_change',
            field=models.BooleanField(default=False),
        ),
    ]
