# Generated by Django 3.2.10 on 2024-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20241123_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
