# Generated by Django 3.2.10 on 2024-12-01 22:02

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20241125_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[myapp.models.validate_positive_amount]),
        ),
        migrations.AlterField(
            model_name='offerhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='offerhistory',
            index=models.Index(fields=['date'], name='myapp_offer_date_f640b5_idx'),
        ),
        migrations.AddIndex(
            model_name='offerhistory',
            index=models.Index(fields=['status'], name='myapp_offer_status_762d77_idx'),
        ),
    ]
