# Generated by Django 3.2.10 on 2024-12-01 22:35

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20241201_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='action_type',
            field=models.CharField(choices=[('live_load', 'Live Load'), ('dropped_trailer', 'Dropped Trailer'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stop',
            name='estimated_weight',
            field=models.IntegerField(validators=[myapp.models.validate_positive_weight]),
        ),
        migrations.AlterField(
            model_name='stop',
            name='quantity',
            field=models.IntegerField(validators=[myapp.models.validate_positive_quantity]),
        ),
    ]
