# Generated by Django 3.2.10 on 2024-12-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20241201_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='action_type',
            field=models.CharField(choices=[('live_load', 'Live Load'), ('dropped_trailer', 'Dropped Trailer'), ('other', 'Other'), ('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=50),
        ),
    ]
