# Generated by Django 3.2.10 on 2024-12-05 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_carrieruser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='load',
            name='current_location',
            field=models.CharField(blank=True, help_text="Current location of the load in 'latitude,longitude' format", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Required equipment for this load', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='myapp.equipmenttype'),
        ),
        migrations.AddField(
            model_name='load',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the load offer expires', null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='load',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='load',
            name='tracking_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='not_started', help_text="Status of the load's transportation", max_length=20),
        ),
        migrations.AddField(
            model_name='offerhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
