# Generated by Django 3.2.10 on 2024-12-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20241205_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='warnings',
            field=models.ManyToManyField(blank=True, help_text='Advertencias asociadas a esta carga', related_name='loads', to='myapp.Warning'),
        ),
    ]
