# Generated by Django 3.2.10 on 2024-12-06 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20241206_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_warnings', to='myapp.load'),
        ),
        migrations.AddField(
            model_name='warning',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_warnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
