# Generated by Django 5.1.2 on 2024-12-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20241206_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieruser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
