# Generated by Django 3.2.10 on 2024-12-06 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_stop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='loaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
