# Generated by Django 3.2.10 on 2024-12-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_stop_loaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerhistory',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='myapp.carrieruser'),
            preserve_default=False,
        ),
    ]
